blueprint:
  name: HexaOne K1 Keypad Integration (Alarmo Bridge)
  description: >
    Connects Alarmo with the HexaOne K1 Keypad.
    - Forwards Alarmo failed-to-arm events to the keypad.
    - Sends Alarmo ready-to-arm mode updates to the keypad.
  domain: automation
  input:
    alarmo_entity:
      name: Alarmo Alarm Entity
      selector:
        entity:
          domain: alarm_control_panel
    failed_arm_action:
      name: Action for Failed Arm
      description: >
        Action to run when Alarmo reports a failed arm.
        Example: Call your ESPHome `failed_arm` service.
      selector:
        action: {}
    ready_update_action:
      name: Action for Ready Update
      description: >
        Action to run when Alarmo reports ready-to-arm state.
        Example: Call your ESPHome `ready_update` service.
      selector:
        action: {}

mode: parallel
max_exceeded: silent

trigger:
  - platform: event
    event_type: alarmo_failed_to_arm
  - platform: event
    event_type: alarmo_ready_to_arm_modes_updated
    event_data:
      entity_id: !input alarmo_entity

action:
  - choose:
      - conditions: "{{ trigger.event.event_type == 'alarmo_failed_to_arm' }}"
        sequence: !input failed_arm_action

      - conditions: "{{ trigger.event.event_type == 'alarmo_ready_to_arm_modes_updated' }}"
        sequence: !input ready_update_action
